[package]
name = "animus-hev"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
animus-core.workspace = true
argon2.workspace = true
aes-gcm.workspace = true
rand.workspace = true
zeroize.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
parking_lot.workspace = true
