[package]
name = "animus-render"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
animus-physics.workspace = true
animus-core.workspace = true
glam.workspace = true
serde.workspace = true
serde_json.workspace = true
parking_lot.workspace = true
ttf-parser.workspace = true
fontdue.workspace = true
thiserror.workspace = true
tracing.workspace = true
